### ISSUE TITLE
bad validation when an ImportPath has points

### ISSUE THREAD

**Issue by sytabaresa** [dpolansky/go-poet#3]
hello, i have issues when i want to use poet with packages that has points
for example when i import this package in my poet file:
```go
import "github.com/someauthor/somepackage"
```
and it's use with poet:
```go
.Statement("$T(params)",poet.TypeReferenceFromInstance(somepackage.SomeFunction))
```

generates:
```go
...
import (
    "github"
)
...{
   github.com/someauthor/somepackage(params)
...}

```
which it is obviously invalid.

I think that the problem is in line 207 in types.go (and maybe in others places):
```go
fullyQualifiedPieces := strings.Split(funcPtr.Name(), ".")
```
witch split the path of a newTypeReferenceFromFunction incorrectly.

thanks!

**Comment by dpolansky** [comment]
Thanks for catching this! We handle functions differently than values and we did not take external packages into account. This should be fixed.
